ALTER TABLE users
  ADD COLUMN photo MEDIUMTEXT NULL,
  ADD COLUMN birth_date DATE NULL,
  ADD COLUMN gender VARCHAR(30) NOT NULL DEFAULT '',
  ADD COLUMN province VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT '';
