ALTER TABLE competitions
  ADD COLUMN category VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN level VARCHAR(50) NOT NULL DEFAULT '',
  ADD COLUMN badges VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN quota INT NOT NULL DEFAULT 0,
  ADD COLUMN original_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN registration_deadline DATETIME NULL;
