CREATE TABLE IF NOT EXISTS teams (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NULL,
  name VARCHAR(150) NOT NULL,
  leader_name VARCHAR(150) NOT NULL DEFAULT '',
  leader_email VARCHAR(150) NOT NULL DEFAULT '',
  leader_phone VARCHAR(30) NOT NULL DEFAULT '',
  leader_nisn VARCHAR(30) NOT NULL DEFAULT '',
  leader_kelas VARCHAR(10) NOT NULL DEFAULT '',
  member1_name VARCHAR(150) NOT NULL DEFAULT '',
  member1_email VARCHAR(150) NOT NULL DEFAULT '',
  member1_nisn VARCHAR(30) NOT NULL DEFAULT '',
  member1_kelas VARCHAR(10) NOT NULL DEFAULT '',
  member2_name VARCHAR(150) NOT NULL DEFAULT '',
  member2_email VARCHAR(150) NOT NULL DEFAULT '',
  member2_nisn VARCHAR(30) NOT NULL DEFAULT '',
  member2_kelas VARCHAR(10) NOT NULL DEFAULT '',
  institution VARCHAR(150) NOT NULL DEFAULT '',
  province VARCHAR(100) NOT NULL DEFAULT '',
  city VARCHAR(100) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  guardian_name VARCHAR(150) NOT NULL DEFAULT '',
  guardian_hp VARCHAR(30) NOT NULL DEFAULT '',
  guardian_email VARCHAR(150) NOT NULL DEFAULT '',
  category ENUM('Olimpiade', 'LKTI', 'Umum') NOT NULL DEFAULT 'Umum',
  status ENUM('active', 'inactive', 'disqualified') NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_teams_name (name),
  INDEX idx_teams_category (category),
  INDEX idx_teams_status (status),
  INDEX idx_teams_user_id (user_id),
  CONSTRAINT fk_teams_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
